.TH SXKBL 1 sxkbl\-VERSION
.SH NAME
sxkbl \- simple X keyboard layout viewer
.SH SYNOPSIS
.B sxkbl
[
.B \-l
]
[
.B \-u
]
[
.B \-v
]
.SH DESCRIPTION
.B sxkbl
prints the actual X keyboard layout. By defaul, sxkbl outputs the short two letters
title, e.g.
.IR En
or
.IR Ru .
.SH OPTIONS
.TP
.B \-l
outputs long layout title, e.g.
.IR "English (US)" .
.TP
.B \-u
prints layout tile with uppercased letters, e.g.
.IR EN .
.TP
.B \-v
prints version information.
